In [10]:
#importation des données /chargement du fichier
import pandas  as pd
df = pd.read_csv('C:/Users/HP/Desktop/Fichiers Finaux/DimPatientCoded.csv',sep=",",header=0)
df

Unnamed: 0 Date Announced  Age Bracket  Age  Gender  Current Status  \
0                0      1/30/2020            0  1.0       0               1   
1                1       2/2/2020            0  1.0       1               1   
2                2       2/3/2020            0  1.0       1               1   
3                3       3/2/2020            0  1.0       1               1   
4                4       3/2/2020            0  1.0       1               1   
...            ...            ...          ...  ...     ...             ...   
247231      247231       8/6/2020            0  1.0       1               1   
247232      247232       8/6/2020            0  1.0       1               1   
247233      247233       8/6/2020            0  1.0       1               1   
247234      247234       8/6/2020            0  1.0       1               1   
247235      247235      7/18/2020            0  1.0       1               1   

        Type of trans Nationality  Symptoms  JobLoss  FinancialSituation  \
0                   1       India         1        2                   1   
1                   1       India         5        0                   0   
2                   1       India         1        2                   1   
3                   1       India         2        2                   0   
4                   1       India         2        0                   1   
...               ...         ...       ...      ...                 ...   
247231              0       India         2        2                   0   
247232              0       India         5        2                   0   
247233              0       India         5        0                   1   
247234              0       India         5        0                   1   
247235              0       India         1        2                   1   

        Diseases  Profession  CovidAfterVaccin  Vaccinated  Reason  
0              4           1                 0           1     0.0  
1              4           2                 1           1     0.0  
2              4           1                 0           1     0.0  
3              2           1                 0           0     2.0  
4              4           2                 0           0     4.0  
...          ...         ...               ...         ...     ...  
247231         4           1                 1           1     0.0  
247232         2           1                 0           0     5.0  
247233         2           2                 0           0     2.0  
247234         2           2                 0           1     0.0  
247235         4           1                 0           0     3.0  

[247236 rows x 16 columns]

In [11]:
del df["Date Announced"]
del df["Unnamed: 0"]
del df["Nationality"]

In [12]:
# vérifions le type d
print(type(df))

<class 'pandas.core.frame.DataFrame'>


In [13]:
#dimensions : nombre de lignes, nombre de colonnes
print(df.shape)

(247236, 13)


In [14]:
#Les noms des colonnes
print(df.columns)

Index(['Age Bracket', 'Age', 'Gender', 'Current Status', 'Type of trans',
       'Symptoms', 'JobLoss', 'FinancialSituation', 'Diseases', 'Profession',
       'CovidAfterVaccin', 'Vaccinated', 'Reason'],
      dtype='object')


In [15]:
#Type de chaque colonne
print(df.dtypes)

Age Bracket             int64
Age                   float64
Gender                  int64
Current Status          int64
Type of trans           int64
Symptoms                int64
JobLoss                 int64
FinancialSituation      int64
Diseases                int64
Profession              int64
CovidAfterVaccin        int64
Vaccinated              int64
Reason                float64
dtype: object


In [16]:
#Description des données
print(df.describe())

         Age Bracket            Age         Gender  Current Status  \
count  247236.000000  247236.000000  247236.000000   247236.000000   
mean        2.291503      33.724118       0.844659        0.378565   
std         1.023251      12.068579       0.362432        0.581446   
min         0.000000       1.000000       0.000000        0.000000   
25%         2.000000      30.000000       1.000000        0.000000   
50%         2.000000      30.000000       1.000000        0.000000   
75%         2.000000      34.000000       1.000000        1.000000   
max         5.000000     105.000000       2.000000        3.000000   

       Type of trans       Symptoms        JobLoss  FinancialSituation  \
count  247236.000000  247236.000000  247236.000000       247236.000000   
mean        0.005137       1.746060       0.809858            0.609608   
std         0.071487       1.537405       0.867908            0.709822   
min         0.000000       0.000000       0.000000            0.000000   

In [17]:
# valeurs de toutes les colonnes
#colonnes => 0:5 (0 à 5 [non inclus])
#lignes = : (toutes les colonnes)
#gender
V_SansLabels=df.iloc[:,1:3];
#Labels
V_Labels=df.iloc[:,3];

In [20]:
#k-means 
import numpy as np
from sklearn import cluster 
kmeans = cluster.KMeans(n_clusters=4);
kmeans.fit(V_SansLabels);
#index triés des groupes 
idk = np.argsort(kmeans.labels_);
#affichage des observations et leurs groupes 
print(pd.DataFrame(V_SansLabels.index[idk],kmeans.labels_[idk]));
kmeans.labels_
#distances aux centres de classes des observations 
print(kmeans.transform(V_SansLabels));
#correspondance avec les groupes réels 
pd.crosstab(V_Labels,kmeans.labels_)

         0
0   123617
0   131534
0   131535
0   131536
0   131537
..     ...
3    11721
3    11722
3    11723
3    11717
3   247235

[247236 rows x 1 columns]
[[29.07889461 45.95695894 64.94559715 13.71344304]
 [29.06749041 45.95031342 64.93838299 13.68221568]
 [29.06749041 45.95031342 64.93838299 13.68221568]
 ...
 [29.06749041 45.95031342 64.93838299 13.68221568]
 [29.06749041 45.95031342 64.93838299 13.68221568]
 [29.06749041 45.95031342 64.93838299 13.68221568]]


col_0                0      1     2     3
Current Status                           
0               129302  20857  8005  8029
1                43240   9687  6203  9520
2                 7103   1851  3239    41
3                   89     23    46     1

In [ ]:
#librairie pour évaluation des partitions
from sklearn import metrics

#utilisation de la métrique "silhouette"
#faire varier le nombre de clusters de 2 à 10
res = np.arange(9,dtype="double")
for k in np.arange(9):
  km = cluster.KMeans(n_clusters=k+2)
  km.fit(V_SansLabels)
  res[k] = metrics.silhouette_score(V_SansLabels,km.labels_)
print(res)
#graphique
import matplotlib.pyplot as plt
plt.title("Silhouette")
plt.xlabel("# of clusters")
plt.plot(np.arange(2,11,1),res)
plt.show()