In [20]:
#importation des données /chargement du fichier
import pandas 
df = pandas.read_csv("DimPatientCoded.csv",sep=",",header=0)
df

Unnamed: 0  gender  status nationality  Transmission  ageBracket  \
0                0       0       0       India             1           0   
1                1       1       0       India             1           0   
2                2       1       1       India             1           0   
3                3       1       2       India             1           0   
4                4       1       0       India             1           0   
...            ...     ...     ...         ...           ...         ...   
247231      247231       1       0       India             0           0   
247232      247232       1       2       India             0           0   
247233      247233       1       2       India             0           0   
247234      247234       1       2       India             0           0   
247235      247235       1       0       India             0           0   

        Symptoms  JobLoss  SituationFin  Disease  Profession  \
0              1        0             1        0           1   
1              5        0             0        0           2   
2              1        0             1        1           1   
3              2        0             0        2           1   
4              2        0             1        0           2   
...          ...      ...           ...      ...         ...   
247231         2        0             0        0           1   
247232         5        0             0        2           1   
247233         5        0             1        2           2   
247234         5        0             1        2           2   
247235         1        0             1        0           1   

        SickAfterVaccine  Vaccinated  Raison  
0                      0           1     0.0  
1                      1           1     0.0  
2                      0           1     0.0  
3                      0           0     2.0  
4                      0           0     4.0  
...                  ...         ...     ...  
247231                 1           1     0.0  
247232                 0           0     5.0  
247233                 0           0     2.0  
247234                 0           1     0.0  
247235                 0           0     3.0  

[247236 rows x 14 columns]

In [21]:
# vérifions le type 
print(type(df))

<class 'pandas.core.frame.DataFrame'>


In [22]:
#dimensions : nombre de lignes, nombre de colonnes
print(df.shape)

(247236, 14)


In [23]:
#Les noms des colonnes
print(df.columns)

Index(['Unnamed: 0', 'gender', 'status', 'nationality', 'Transmission',
       'ageBracket', 'Symptoms', 'JobLoss', 'SituationFin', 'Disease',
       'Profession', 'SickAfterVaccine', 'Vaccinated', 'Raison'],
      dtype='object')


In [24]:
#Type de chaque colonne
print(df.dtypes)

Unnamed: 0            int64
gender                int64
status                int64
nationality          object
Transmission          int64
ageBracket            int64
Symptoms              int64
JobLoss               int64
SituationFin          int64
Disease               int64
Profession            int64
SickAfterVaccine      int64
Vaccinated            int64
Raison              float64
dtype: object


In [25]:
#Description des données
print(df.describe())

          Unnamed: 0         gender         status   Transmission  \
count  247236.000000  247236.000000  247236.000000  247236.000000   
mean   123617.500000       0.844659       1.373578       0.005137   
std     71371.029914       0.362432       1.111535       0.071487   
min         0.000000       0.000000       0.000000       0.000000   
25%     61808.750000       1.000000       0.000000       0.000000   
50%    123617.500000       1.000000       1.000000       0.000000   
75%    185426.250000       1.000000       2.000000       0.000000   
max    247235.000000       2.000000       3.000000       1.000000   

          ageBracket       Symptoms        JobLoss   SituationFin  \
count  247236.000000  247236.000000  247236.000000  247236.000000   
mean        2.291503       1.746060       0.463897       0.619845   
std         1.023251       1.537405       0.498696       0.722477   
min         0.000000       0.000000       0.000000       0.000000   
25%         2.000000       0.0000

In [26]:
import numpy as np
df['Disease'].value_counts()

0    71317
1    64725
2    58709
3    52485
Name: Disease, dtype: int64

In [27]:
df['Symptoms'].value_counts()

0    72761
1    51238
2    40990
3    40813
4    31138
5    10296
Name: Symptoms, dtype: int64

In [28]:
df['Transmission'].value_counts()

0    245966
1      1270
Name: Transmission, dtype: int64

In [29]:
df['Profession'].value_counts()

0    74880
1    48061
2    41178
3    39723
4    37517
5     5877
Name: Profession, dtype: int64

In [30]:
del df['Unnamed: 0']

In [31]:
del df['nationality']

In [32]:
df

gender  status  Transmission  ageBracket  Symptoms  JobLoss  \
0            0       0             1           0         1        0   
1            1       0             1           0         5        0   
2            1       1             1           0         1        0   
3            1       2             1           0         2        0   
4            1       0             1           0         2        0   
...        ...     ...           ...         ...       ...      ...   
247231       1       0             0           0         2        0   
247232       1       2             0           0         5        0   
247233       1       2             0           0         5        0   
247234       1       2             0           0         5        0   
247235       1       0             0           0         1        0   

        SituationFin  Disease  Profession  SickAfterVaccine  Vaccinated  \
0                  1        0           1                 0           1   
1                  0        0           2                 1           1   
2                  1        1           1                 0           1   
3                  0        2           1                 0           0   
4                  1        0           2                 0           0   
...              ...      ...         ...               ...         ...   
247231             0        0           1                 1           1   
247232             0        2           1                 0           0   
247233             1        2           2                 0           0   
247234             1        2           2                 0           1   
247235             1        0           1                 0           0   

        Raison  
0          0.0  
1          0.0  
2          0.0  
3          2.0  
4          4.0  
...        ...  
247231     0.0  
247232     5.0  
247233     2.0  
247234     0.0  
247235     3.0  

[247236 rows x 12 columns]

In [33]:
# valeurs de toutes les colonnes
#colonnes => 0:5 (0 à 5 [non inclus])
#lignes = : (toutes les colonnes)
#gender
V_SansLabels=df.iloc[:,0:8];
#Labels
V_Labels=df.iloc[:,8];

In [34]:
#k-means 
import numpy as np
from sklearn import cluster 
kmeans = cluster.KMeans(n_clusters=5);
kmeans.fit(V_SansLabels);
#index triés des groupes 
idk = np.argsort(kmeans.labels_);
#affichage des observations et leurs groupes 
print(pandas.DataFrame(V_SansLabels.index[idk],kmeans.labels_[idk]));
kmeans.labels_
#distances aux centres de classes des observations 
print(kmeans.transform(V_SansLabels));
#correspondance avec les groupes réels 
pandas.crosstab(V_Labels,kmeans.labels_)

         0
0        0
0    98084
0    98061
0    98059
0    98046
..     ...
4   224615
4   195354
4   224613
4   224629
4   188823

[247236 rows x 1 columns]
[[2.59494787 3.21390804 4.5945425  4.7903298  4.55898304]
 [5.2297175  2.87189641 6.41264957 4.63528345 5.84806241]
 [2.50303822 3.12134443 3.52613774 3.79432389 4.37421264]
 ...
 [5.52480359 3.35482515 5.27551926 2.92003861 5.9370049 ]
 [5.52480359 3.35482515 5.27551926 2.92003861 5.9370049 ]
 [2.25538381 2.93965744 4.41140381 4.61164375 4.3593881 ]]


col_0           0      1      2      3     4
Profession                                  
0           16128  16985  17665  16441  7661
1           10562  14822   9530  10114  3033
2            8714   9852   9443   8626  4543
3            8561   8852   9327   8375  4608
4            8522   8814   8848   8332  3001
5               0      0   1007    181  4689

In [ ]:
#librairie pour évaluation des partitions 
from sklearn import metrics

#utilisation de la métrique "silhouette" 
#faire varier le nombre de clusters de 2 à 10 
res = np.arange(9,dtype="double") 
for k in np.arange(9): 
  km = cluster.KMeans(n_clusters=k+2) 
  km.fit(V_SansLabels) 
  res[k] = metrics.silhouette_score(V_SansLabels,km.labels_)
print(res)
#graphique 
import matplotlib.pyplot as plt 
plt.title("Silhouette") 
plt.xlabel("# of clusters") 
plt.plot(np.arange(2,11,1),res) 
plt.show()